[logger]
    mode = "debug"
    timestamp = "time"

[authorization]
    [[authorization.users]]
        username = "username"
        password = "password"

[api]
    enable = true
    auth = true
    env = "development"

[web]
    enable = true
    [web.static]
        folder = "src/static"

[docker]
    #tags = ["tag1","tag2"]