[logger]                # настройка логгера
    mode = "prod"       # режим (prod или dev или debug)
    enable = true       # активация логгера
    timestamp = "none"  # выводить время лога (none, time или full)
    type = true         # выводить тип лога (true или false)

[authorization]                     # настрока авторизации
    [[authorization.users]]         # массив пользователей
        username = "username"       # имя пользователя
        password = "password"       # пароль пользователя
    [[authorization.users]]         
        token = "xxxxxxxxxxxx"      # токен доступа

[api]                                   # настройка API
    enable = false                      # активация API
    auth = false                        # активация авторизации
    listening = "*:3001"                # настройка слушателя
    prefix = "/api"                     # префикс
    proxy = false                       # когда поле заголовка true proxy будут доверенным
    subdomain_offset = 2                # смещение от поддомена для игнорирования
    proxy_header = "X-Forwarded-For"    # заголовок IP прокси
    ips_count = 0                       # максимальное количество IP прочитанное из заголовка прокси, по умолчанию 0 (означает бесконечность)
    env = "development"                 # среда для сервера koa
    #keys = []                          # массив подписанных ключей cookie

[web]                                   # настройка WEB сервера
    enable = false                      # активация WEB сервера
    auth = false                        # активация авторизации
    listening = "*:3000"                # настройка слушателя
    prefix = ""                         # префикс
    proxy = false                       # когда поле заголовка true proxy будут доверенным
    subdomain_offset = 2                # смещение от поддомена для игнорирования
    proxy_header = "X-Forwarded-For"    # заголовок IP прокси
    ips_count = 0                       # максимальное количество IP прочитанное из заголовка прокси, по умолчанию 0 (означает бесконечность)
    env = "development"                 # среда для сервера koa
    #keys = []                          # массив подписанных ключей cookie
    [web.static]                        # настройка статического сервера (пакет: https://github.com/koajs/static)
        folder = "static"               # папка со статическими файлами
        maxage = 0                      # время жизни кеша в миллисекундах
        hidden = false                  # разрешение отдавать скрытые файлы
        index = "index.html"            # название файла индекса
        defer = false                   # позволить активировать нижестоящие промежуточное по первым
        gzip = true                     # gzip сжатие
        brotli = true                   # автоматическое обслуживание файла brotli

[docker_healthcheck]    # настрока провеки здоровя для контейнера (утилита docker-healthcheck)
    enable = false      # активация
    timeout = 10        # время ожидания

[docker]                                # настройки докера
    label_prefix = "healthcheck"        # префикс меток поиска             
    host = "localhost"                  # хост подключения, игнорируется если указан socket.
    port = 2375                         # порт подключения, игнорируется если указан socket.
    ca = ""                             # путь файла до файла CA, игнорируется если указан socket.
    cert = ""                           # путь до файла сертификата, игнорируется если указан socket.
    key = ""                            # путь до файла ключа, игнорируется если указан socket.
    version = "v1.38"                   # версия api docker
    interval = 10                       # интервал опроса в секундах
    #tags = ["tag1"]                    # теги выборки (не обязательно)
    #socket = "/var/run/docker.sock"    # путь к сокету docker (не обязательно)